### ISSUE TITLE
Volume sliders reset after playing

### ISSUE THREAD

**Issue by Pierre-Demessence** [Pierre-Demessence/NFC-Ball-Maze-Game#32]
The sliders should be initialized with the current volume values so when we come back to the menu after playing, they don't get reset to the default values (which do not reflect the actual volume values).

**Comment by camblomquist** [comment]
These, along with a few other things down the road, will need to be saved either in Player Prefs (which seems to be not as awful in phone builds since they don't use the registry,) or in a custom serialized object storing these values. @Naxane this would be a good learning experience if you haven't dealt with serialization before.
